import type { NicheId } from './types';

export interface Topic {
  id: string;
  label: string;
  /** Anziehungskraft ueber die eigene Nische hinaus (Explore-Potenzial). */
  broad: number;
  /** Wie gut das Thema die eigene Zielgruppe bedient (Bindung, Follower halten). */
  core: number;
}

export interface Niche {
  id: NicheId;
  label: string;
  emoji: string;
  /** Farbwelt fuer die prozedurale Bildgenerierung. */
  palette: string[];
  /** Bildmotiv-Generator, siehe image.ts */
  motif: 'mountain' | 'plate' | 'body' | 'portrait' | 'abstract' | 'grid' | 'skyline' | 'wave' | 'creature' | 'stage' | 'figure';
  /** Wie gross die potenzielle Zielgruppe der Nische ist (0..1). */
  reach: number;
  /** Wie hart der Wettbewerb in der Nische ist (0..1, hoch = schwerer). */
  competition: number;
  topics: Topic[];
  hashtags: string[];
  captions: string[];
  comments: string[];
  bios: string[];
  /** Stile, die optisch zur Nische passen. */
  styles: string[];
}

export const NICHES: Record<NicheId, Niche> = {
  fitness: {
    id: 'fitness',
    label: 'Fitness',
    emoji: '💪',
    palette: ['#ff5f6d', '#ffc371', '#2b2b3c', '#f7f7fa'],
    motif: 'body',
    reach: 0.82,
    competition: 0.78,
    topics: [
      { id: 'transformation', label: 'Transformation vorher/nachher', broad: 0.92, core: 0.88 },
      { id: 'workout', label: 'Workout-Routine', broad: 0.55, core: 0.9 },
      { id: 'mealprep', label: 'Meal Prep Sonntag', broad: 0.48, core: 0.82 },
      { id: 'gymselfie', label: 'Gym-Selfie', broad: 0.42, core: 0.55 },
      { id: 'pr', label: 'Neuer Kraft-Rekord', broad: 0.6, core: 0.85 },
      { id: 'mistakes', label: '5 Fehler, die jeder macht', broad: 0.78, core: 0.8 },
      { id: 'restday', label: 'Rest Day & Regeneration', broad: 0.35, core: 0.68 },
      { id: 'homeworkout', label: 'Home-Workout ohne Geraete', broad: 0.74, core: 0.79 },
    ],
    hashtags: ['fitness', 'gym', 'training', 'fitfam', 'homeworkout', 'krafttraining', 'gesundleben', 'muskelaufbau', 'transformation', 'fitnessmotivation', 'mealprep', 'cardio', 'pushday', 'legday'],
    captions: [
      'Tag {n} von {n2}. Kein Tag war umsonst. {emoji}',
      'Ehrlich? Ich hatte heute null Bock. Trotzdem gemacht. Das ist der ganze Trick. {emoji}',
      'Speicher dir das ab, wenn du {topic} endlich verstehen willst.',
      '{topic} - so mache ich es seit 2 Jahren. Frag mich alles in den Kommentaren.',
      'Vor 12 Monaten haette ich das nicht geschafft. Heute ist es Aufwaermen. {emoji}',
      'Der Unterschied zwischen dir und dem Ergebnis: {n} Wochen Konsequenz.',
    ],
    comments: [
      'Das ist ja mal Motivation pur 🔥',
      'Wie viele Saetze machst du da?',
      'Respekt, das sieht nach richtig viel Arbeit aus 💪',
      'Bin seit heute dabei, danke dir!',
      'Endlich mal jemand ohne Bullshit-Versprechen',
      'Speicher ich mir direkt ab',
    ],
    bios: [
      'Coach | Kraft & Kopf | Dein Plan: Link in Bio',
      'Von 0 auf 100kg Bankdruecken 🏋️ Ich zeig dir wie',
      'Training ist Therapie. Taeglich neue Workouts.',
      'Zertifizierte Trainerin 🇩🇪 | Home Workouts fuer echte Menschen',
    ],
    styles: ['vivid', 'studio', 'mono'],
  },
  food: {
    id: 'food',
    label: 'Food',
    emoji: '🍜',
    palette: ['#f6d365', '#fda085', '#7a3b2e', '#fff8ef'],
    motif: 'plate',
    reach: 0.95,
    competition: 0.72,
    topics: [
      { id: 'rezept', label: '3-Zutaten-Rezept', broad: 0.9, core: 0.86 },
      { id: 'streetfood', label: 'Streetfood-Entdeckung', broad: 0.82, core: 0.7 },
      { id: 'backen', label: 'Backen mit Fail-Garantie', broad: 0.71, core: 0.78 },
      { id: 'restaurant', label: 'Restaurant-Review', broad: 0.6, core: 0.74 },
      { id: 'meal', label: 'Was ich an einem Tag esse', broad: 0.77, core: 0.8 },
      { id: 'omas', label: 'Omas Rezept neu gedacht', broad: 0.86, core: 0.9 },
      { id: 'vegan', label: 'Vegan & in 10 Minuten', broad: 0.74, core: 0.83 },
      { id: 'kaffee', label: 'Der perfekte Kaffee', broad: 0.52, core: 0.6 },
    ],
    hashtags: ['food', 'foodie', 'rezept', 'kochen', 'homemade', 'foodstagram', 'backen', 'vegan', 'streetfood', 'soulfood', 'mealprep', 'kaffee', 'bruch', 'hungrig'],
    captions: [
      'Das Rezept ist so einfach, dass es fast schon peinlich ist. {emoji} Speichern!',
      '{topic}. Ich habe {n} Versuche gebraucht. Der letzte war es wert.',
      'Zutaten in den Kommentaren. Wer probiert es nach?',
      'Ich sage nur: {n} Minuten, eine Pfanne, kein Abwasch-Drama. {emoji}',
      'Meine Oma wuerde mich dafuer schlagen. Schmeckt trotzdem grandios.',
      'Nichts Fancy. Nur gutes Essen und ein ehrlicher Teller. {emoji}',
    ],
    comments: [
      'Okay das mache ich heute Abend nach 😍',
      'Rezept bitte!! 🙏',
      'Der Teller sieht besser aus als im Restaurant',
      'Zu viel Salz? Nie. Perfekt.',
      'Ich rieche das durch den Bildschirm',
      'Speicher Nr. 47 diese Woche von dir 😅',
    ],
    bios: [
      'Kochen ohne Regeln 🍳 Rezepte taeglich',
      'Isst sich durch Berlin 🍜 Ehrliche Reviews',
      'Backen ist Mathe mit Butter 🧈',
      'Vegan, schnell, guenstig. Kein Schnickschnack.',
    ],
    styles: ['golden', 'vivid', 'film'],
  },
  travel: {
    id: 'travel',
    label: 'Reisen',
    emoji: '✈️',
    palette: ['#4facfe', '#00f2fe', '#1b3b5a', '#fdfcfb'],
    motif: 'mountain',
    reach: 0.93,
    competition: 0.85,
    topics: [
      { id: 'geheimtipp', label: 'Geheimtipp ohne Touristen', broad: 0.94, core: 0.9 },
      { id: 'budget', label: 'Eine Woche unter 300 Euro', broad: 0.88, core: 0.84 },
      { id: 'sonnenaufgang', label: 'Sonnenaufgang am Aussichtspunkt', broad: 0.7, core: 0.72 },
      { id: 'roadtrip', label: 'Roadtrip-Route', broad: 0.76, core: 0.86 },
      { id: 'vanlife', label: 'Vanlife-Alltag', broad: 0.68, core: 0.8 },
      { id: 'packliste', label: 'Packliste, die wirklich reicht', broad: 0.64, core: 0.78 },
      { id: 'fail', label: 'Das ging schief auf der Reise', broad: 0.8, core: 0.66 },
      { id: 'hotel', label: 'Hotel-Check', broad: 0.5, core: 0.62 },
    ],
    hashtags: ['travel', 'reisen', 'wanderlust', 'roadtrip', 'vanlife', 'fernweh', 'geheimtipp', 'backpacking', 'sonnenaufgang', 'europa', 'abenteuer', 'traveldiary', 'wandern', 'reisetipps'],
    captions: [
      'Dieser Ort steht auf keiner Karte. Bitte behaltet ihn fuer euch. {emoji}',
      '{n} Stunden Zug, 4 Grad, keine Reservierung. Wuerde ich sofort wieder machen.',
      '{topic} - alle Infos im naechsten Post. Fragt einfach.',
      'Ich habe {n} Euro fuer diese Woche ausgegeben. Alles.',
      'Kein Filter faengt das ein. Trotzdem versuche ich es. {emoji}',
      'Manchmal ist der Umweg das Ziel. Kitschig? Ja. Wahr? Auch.',
    ],
    comments: [
      'Wo genau ist das?? 😍',
      'Direkt auf die Bucket List damit',
      'Deine Bilder sind jedes Mal ein Traum',
      'Wie lange warst du unterwegs?',
      'Das Licht da. Wahnsinn.',
      'Nehme ich als Zeichen, endlich zu buchen',
    ],
    bios: [
      '🌍 47 Laender | Reisen ohne Reichtum',
      'Van + Kamera + kein Plan 🚐',
      'Zeige dir Europa abseits der Massen',
      'Fernweh ist ein Dauerzustand ✈️',
    ],
    styles: ['golden', 'vivid', 'film'],
  },
  fashion: {
    id: 'fashion',
    label: 'Fashion',
    emoji: '👗',
    palette: ['#e8c1c7', '#8e6d7f', '#20161c', '#f3ece9'],
    motif: 'figure',
    reach: 0.87,
    competition: 0.88,
    topics: [
      { id: 'outfit', label: 'Outfit des Tages', broad: 0.6, core: 0.82 },
      { id: 'thrift', label: 'Secondhand-Haul', broad: 0.85, core: 0.88 },
      { id: 'capsule', label: 'Capsule Wardrobe', broad: 0.7, core: 0.86 },
      { id: 'dupes', label: 'Teuer vs. guenstig', broad: 0.9, core: 0.78 },
      { id: 'styling', label: 'Ein Teil, fuenf Looks', broad: 0.83, core: 0.9 },
      { id: 'runway', label: 'Fashion Week Eindruecke', broad: 0.66, core: 0.7 },
      { id: 'diy', label: 'Kleidung selbst umnaehen', broad: 0.78, core: 0.74 },
      { id: 'shoes', label: 'Sneaker-Sammlung', broad: 0.55, core: 0.62 },
    ],
    hashtags: ['fashion', 'ootd', 'style', 'secondhand', 'thrift', 'outfitinspo', 'slowfashion', 'streetstyle', 'vintage', 'lookbook', 'capsulewardrobe', 'modeblog', 'sneaker', 'trend'],
    captions: [
      'Komplettes Outfit: {n} Euro. Secondhand. {emoji}',
      '{topic} - welches Teil wuerdet ihr behalten?',
      'Ich trage diesen Mantel jetzt seit {n} Jahren. Beste Investition ever.',
      'Trends sind mir egal, aber dieser hier... okay, erwischt. {emoji}',
      'Ein Teil, fuenf Looks. Speichern nicht vergessen.',
      'Style ist, was uebrig bleibt, wenn der Trend weg ist.',
    ],
    comments: [
      'Woher ist der Mantel?? 😍',
      'Look 3 ist der beste, ganz klar',
      'Du machst aus allem ein Statement',
      'Secondhand-Queen 👑',
      'Ich brauche diese Schuhe sofort',
      'Deine Farbkombis sind immer so gut',
    ],
    bios: [
      'Slow Fashion | Secondhand only ♻️',
      'Mode aus dem Kleiderschrank, nicht aus dem Laden',
      'Styling-Tipps fuer echte Budgets 👗',
      'Berlin | Vintage | zu viele Maentel',
    ],
    styles: ['film', 'pastel', 'studio'],
  },
  art: {
    id: 'art',
    label: 'Kunst',
    emoji: '🎨',
    palette: ['#a18cd1', '#fbc2eb', '#231942', '#fef6ff'],
    motif: 'abstract',
    reach: 0.72,
    competition: 0.55,
    topics: [
      { id: 'prozess', label: 'Entstehungsprozess im Zeitraffer', broad: 0.88, core: 0.9 },
      { id: 'skizze', label: 'Skizzenbuch-Seite', broad: 0.5, core: 0.8 },
      { id: 'fertig', label: 'Fertiges Werk', broad: 0.66, core: 0.85 },
      { id: 'atelier', label: 'Atelier-Einblick', broad: 0.58, core: 0.72 },
      { id: 'tutorial', label: 'Technik erklaert', broad: 0.8, core: 0.88 },
      { id: 'fail', label: 'Was ich weggeworfen habe', broad: 0.72, core: 0.68 },
      { id: 'commission', label: 'Auftragsarbeit', broad: 0.48, core: 0.6 },
      { id: 'material', label: 'Materialtest', broad: 0.55, core: 0.7 },
    ],
    hashtags: ['kunst', 'art', 'illustration', 'artistsoninstagram', 'malerei', 'sketchbook', 'acryl', 'digitalart', 'prozess', 'atelier', 'kreativ', 'zeichnung', 'artwork', 'inspiration'],
    captions: [
      '{n} Stunden. Drei Uebermalungen. Jetzt darf es raus. {emoji}',
      'Prozess statt Ergebnis. Wer will ein Tutorial dazu?',
      '{topic}. Materialien in den Kommentaren.',
      'Ich war kurz davor, das wegzuwerfen. Gut, dass ich es nicht getan habe.',
      'Farbe ist Stimmung. Heute: {emoji}',
      'Kunst muss nicht gefallen. Aber ihr duerft trotzdem liken.',
    ],
    comments: [
      'Die Farben! 😍',
      'Wie lange hast du daran gesessen?',
      'Der Prozess ist fast schoener als das Ergebnis',
      'Verkaufst du Prints?',
      'Das gehoert in eine Galerie',
      'Deine Handschrift erkennt man sofort',
    ],
    bios: [
      'Acryl & Chaos 🎨 Prints verfuegbar',
      'Illustratorin | Auftraege offen',
      'Male, weil reden schwer ist',
      'Digital & analog | Atelier Leipzig',
    ],
    styles: ['vivid', 'pastel', 'moody'],
  },
  photo: {
    id: 'photo',
    label: 'Fotografie',
    emoji: '📷',
    palette: ['#232526', '#414345', '#c9c9c9', '#f5f5f5'],
    motif: 'skyline',
    reach: 0.78,
    competition: 0.7,
    topics: [
      { id: 'street', label: 'Street Photography', broad: 0.74, core: 0.86 },
      { id: 'portrait', label: 'Portraitshooting', broad: 0.7, core: 0.84 },
      { id: 'edit', label: 'Vorher/Nachher Bearbeitung', broad: 0.9, core: 0.88 },
      { id: 'gear', label: 'Equipment-Talk', broad: 0.52, core: 0.72 },
      { id: 'analog', label: 'Analoge Filmrolle', broad: 0.64, core: 0.8 },
      { id: 'settings', label: 'Einstellungen erklaert', broad: 0.76, core: 0.9 },
      { id: 'bluehour', label: 'Blaue Stunde', broad: 0.68, core: 0.76 },
      { id: 'behind', label: 'Behind the Scenes', broad: 0.72, core: 0.7 },
    ],
    hashtags: ['fotografie', 'photography', 'streetphotography', 'portrait', 'analog', 'lightroom', 'blauestunde', 'bildbearbeitung', 'canon', 'sony', 'fotografieren', 'bnw', 'composition', 'photooftheday'],
    captions: [
      '1/{n}s, f/1.8, ISO 400. Kein Blitz, nur Geduld. {emoji}',
      'Vorher rechts, nachher links. Gleiche Datei.',
      '{topic}. Die Szene war in 4 Sekunden vorbei.',
      'Beste Kamera ist die, die du dabei hast. Trotzdem: das hier war die grosse.',
      'Licht kann man nicht kaufen. Nur abwarten. {emoji}',
      'Ein Bild aus 340. Der Rest bleibt auf der Karte.',
    ],
    comments: [
      'Komposition ist perfekt 👌',
      'Welche Kamera nutzt du?',
      'Das Licht in diesem Bild...',
      'Bearbeitest du in Lightroom?',
      'Mega Timing!',
      'Sieht aus wie ein Filmstill',
    ],
    bios: [
      'Straße, Licht, Zufall 📷',
      'Analog seit 2016 | 35mm Fan',
      'Portraits & Hochzeiten | Anfragen per DM',
      'Fotografieren lernen ohne Gatekeeping',
    ],
    styles: ['mono', 'film', 'moody'],
  },
  tech: {
    id: 'tech',
    label: 'Tech',
    emoji: '💻',
    palette: ['#0f2027', '#2c5364', '#00c6ff', '#e8f6ff'],
    motif: 'grid',
    reach: 0.8,
    competition: 0.62,
    topics: [
      { id: 'setup', label: 'Schreibtisch-Setup', broad: 0.82, core: 0.84 },
      { id: 'review', label: 'Geraete-Review', broad: 0.7, core: 0.8 },
      { id: 'tipps', label: '5 Tricks, die keiner kennt', broad: 0.9, core: 0.88 },
      { id: 'ki', label: 'KI-Tool ausprobiert', broad: 0.92, core: 0.82 },
      { id: 'code', label: 'Code-Snippet erklaert', broad: 0.55, core: 0.86 },
      { id: 'budget', label: 'Guenstige Alternative', broad: 0.86, core: 0.8 },
      { id: 'fail', label: 'Tech-Fail des Monats', broad: 0.74, core: 0.62 },
      { id: 'zukunft', label: 'Was 2027 normal sein wird', broad: 0.8, core: 0.7 },
    ],
    hashtags: ['tech', 'setup', 'gadgets', 'ki', 'coding', 'productivity', 'homeoffice', 'review', 'technik', 'software', 'apple', 'linux', 'nerd', 'workspace'],
    captions: [
      '{n} Euro gespart, weil ich diesen Trick kenne. Speichern! {emoji}',
      '{topic}. Ehrliche Meinung, kein bezahlter Post.',
      'Ich habe das 3 Wochen getestet. Fazit in den Kommentaren.',
      'Setup-Update. Ja, die Kabel sind immer noch ein Drama. {emoji}',
      'Wer das noch nicht kennt, arbeitet gerade zu viel von Hand.',
      'Kurz gesagt: gut, aber nicht fuer jeden. Details unten.',
    ],
    comments: [
      'Wusste ich nicht, danke!',
      'Welche Tastatur ist das?',
      'Endlich mal ein ehrliches Review',
      'Direkt nachgebaut, funktioniert 🙌',
      'Das spart mir Stunden',
      'Linux-User melden sich 🐧',
    ],
    bios: [
      'Tech ohne Hype | Reviews & Tricks',
      'Baue Dinge, die kaputt gehen 💻',
      'Software-Entwicklerin | erklaert Code einfach',
      'Setup-Nerd | Homeoffice-Optimierer',
    ],
    styles: ['neon', 'studio', 'mono'],
  },
  gaming: {
    id: 'gaming',
    label: 'Gaming',
    emoji: '🎮',
    palette: ['#7f00ff', '#e100ff', '#12002e', '#f0e6ff'],
    motif: 'grid',
    reach: 0.85,
    competition: 0.74,
    topics: [
      { id: 'clip', label: 'Clutch-Moment', broad: 0.86, core: 0.9 },
      { id: 'review', label: 'Spiele-Review', broad: 0.66, core: 0.82 },
      { id: 'setup', label: 'Gaming-Setup', broad: 0.72, core: 0.78 },
      { id: 'speedrun', label: 'Speedrun-Versuch', broad: 0.7, core: 0.84 },
      { id: 'indie', label: 'Indie-Perle entdeckt', broad: 0.74, core: 0.86 },
      { id: 'rant', label: 'Warum das Update Mist ist', broad: 0.82, core: 0.7 },
      { id: 'nostalgie', label: 'Retro-Nostalgie', broad: 0.88, core: 0.8 },
      { id: 'tipps', label: 'Anfaenger-Guide', broad: 0.78, core: 0.88 },
    ],
    hashtags: ['gaming', 'gamer', 'indiegames', 'retrogaming', 'speedrun', 'letsplay', 'gamingsetup', 'twitch', 'esport', 'pcgaming', 'konsole', 'clip', 'gameplay', 'zocken'],
    captions: [
      'Ton an. Sekunde {n}. Ihr werdet es merken. {emoji}',
      '{topic} - und ja, ich habe {n} Versuche gebraucht.',
      'Dieses Indie-Spiel hat mehr Herz als jeder 80-Euro-Titel.',
      'Kein Aim, nur Glueck. Nehme ich trotzdem. {emoji}',
      'Wer das damals gespielt hat, ist jetzt offiziell alt.',
      'Patch Notes gelesen. Wir muessen reden.',
    ],
    comments: [
      'Das war krank 😂',
      'Welches Spiel ist das?',
      'Mein Kindheitstrauma, danke',
      'Clip des Monats ehrlich',
      'Dein Aim ist unmenschlich',
      'Spiele ich seit Jahren, wusste ich nicht',
    ],
    bios: [
      'Zocke, seit es Pixel gibt 🎮',
      'Indie-Games & schlechte Entscheidungen',
      'Speedrunner | WR-Jagd laeuft',
      'Twitch: taeglich ab 20 Uhr',
    ],
    styles: ['neon', 'vivid', 'moody'],
  },
  music: {
    id: 'music',
    label: 'Musik',
    emoji: '🎧',
    palette: ['#ff0844', '#ffb199', '#16000f', '#fff0f5'],
    motif: 'stage',
    reach: 0.88,
    competition: 0.8,
    topics: [
      { id: 'studio', label: 'Studio-Session', broad: 0.7, core: 0.86 },
      { id: 'live', label: 'Live-Auftritt', broad: 0.84, core: 0.88 },
      { id: 'cover', label: 'Cover-Version', broad: 0.88, core: 0.82 },
      { id: 'beat', label: 'Beat-Making', broad: 0.72, core: 0.85 },
      { id: 'release', label: 'Neue Single', broad: 0.66, core: 0.9 },
      { id: 'vinyl', label: 'Plattensammlung', broad: 0.6, core: 0.7 },
      { id: 'story', label: 'Geschichte hinter dem Song', broad: 0.82, core: 0.88 },
      { id: 'jam', label: 'Spontane Jam-Session', broad: 0.76, core: 0.78 },
    ],
    hashtags: ['musik', 'music', 'newmusic', 'livemusic', 'cover', 'produzent', 'beats', 'vinyl', 'songwriting', 'studio', 'indiemusic', 'gitarre', 'singer', 'sound'],
    captions: [
      'Songtext ist in 20 Minuten entstanden. Manchmal geht es einfach. {emoji}',
      '{topic}. Ganzer Song ab Freitag ueberall.',
      'Der Raum war voll, ich war fertig, es war perfekt.',
      'Erste Version vs. finale Version. Hoert ihr den Unterschied?',
      'Dieser Beat lag {n} Monate auf der Festplatte. Zeit wurde es. {emoji}',
      'Musik ist die einzige Luege, die die Wahrheit sagt.',
    ],
    comments: [
      'Gaensehaut ehrlich 🔥',
      'Wann kommt die volle Version?',
      'Deine Stimme ist unglaublich',
      'Der Beat geht sofort ins Ohr',
      'Hab das 12 mal hintereinander gehoert',
      'Spotify-Link bitte!',
    ],
    bios: [
      'Produzent | Beats & Bass 🎧',
      'Singer/Songwriter | neue EP draussen',
      'Musik machen statt reden 🎸',
      'Live jeden Freitag irgendwo in NRW',
    ],
    styles: ['neon', 'moody', 'film'],
  },
  pets: {
    id: 'pets',
    label: 'Tiere',
    emoji: '🐕',
    palette: ['#ffecd2', '#fcb69f', '#5b3a29', '#fffaf3'],
    motif: 'creature',
    reach: 0.97,
    competition: 0.6,
    topics: [
      { id: 'alltag', label: 'Alltagsmoment', broad: 0.78, core: 0.84 },
      { id: 'trick', label: 'Neuer Trick gelernt', broad: 0.88, core: 0.88 },
      { id: 'welpe', label: 'Welpen-Update', broad: 0.95, core: 0.9 },
      { id: 'fail', label: 'Chaos angerichtet', broad: 0.92, core: 0.8 },
      { id: 'tierarzt', label: 'Beim Tierarzt', broad: 0.6, core: 0.72 },
      { id: 'adoption', label: 'Adoptionsgeschichte', broad: 0.9, core: 0.92 },
      { id: 'schlaf', label: 'Schlafende Fellnase', broad: 0.7, core: 0.66 },
      { id: 'tipps', label: 'Erziehungstipp', broad: 0.66, core: 0.86 },
    ],
    hashtags: ['hund', 'katze', 'pets', 'dogsofinstagram', 'catsofinstagram', 'tierliebe', 'welpe', 'fellnase', 'tierschutz', 'adoptdontshop', 'hundeliebe', 'tiere', 'haustier', 'doglife'],
    captions: [
      'Er hat es wieder getan. Das ist Sofa Nummer {n}. {emoji}',
      '{topic}. Ich glaube, er versteht mehr als er zugibt.',
      'Vor {n} Jahren aus dem Tierheim. Beste Entscheidung meines Lebens.',
      'Kein Text noetig. Schaut euch dieses Gesicht an. {emoji}',
      'Drei Wochen geuebt. Heute hat es geklappt!',
      '10 Sekunden Ruhe pro Tag. Das hier ist sie.',
    ],
    comments: [
      'Ich sterbe, wie suess 😭',
      'Das Gesicht! 😍',
      'Wie alt ist der Kleine?',
      'Tierheim-Hunde sind die besten ❤️',
      'Mein Herz ist geschmolzen',
      'Darf ich ihn ausleihen?',
    ],
    bios: [
      'Golden Retriever mit eigenem Account 🐕',
      'Zwei Katzen, null Kontrolle 🐈',
      'Tierschutz-Hund aus Rumaenien ❤️',
      'Hundetrainerin | positiv verstaerkt',
    ],
    styles: ['vivid', 'golden', 'pastel'],
  },
  beauty: {
    id: 'beauty',
    label: 'Beauty',
    emoji: '💄',
    palette: ['#fbc2eb', '#a6c1ee', '#2b1b2b', '#fff5fb'],
    motif: 'portrait',
    reach: 0.9,
    competition: 0.9,
    topics: [
      { id: 'routine', label: 'Skincare-Routine', broad: 0.8, core: 0.88 },
      { id: 'tutorial', label: 'Make-up Tutorial', broad: 0.78, core: 0.9 },
      { id: 'drogerie', label: 'Drogerie vs. Luxus', broad: 0.92, core: 0.84 },
      { id: 'haare', label: 'Haar-Transformation', broad: 0.9, core: 0.82 },
      { id: 'nomakeup', label: 'Ungeschminkt & ehrlich', broad: 0.86, core: 0.8 },
      { id: 'fails', label: 'Beauty-Mythen entlarvt', broad: 0.88, core: 0.86 },
      { id: 'nails', label: 'Nageldesign', broad: 0.62, core: 0.74 },
      { id: 'inci', label: 'Inhaltsstoffe erklaert', broad: 0.64, core: 0.9 },
    ],
    hashtags: ['beauty', 'skincare', 'makeup', 'hautpflege', 'drogerie', 'glowup', 'tutorial', 'nails', 'haare', 'selfcare', 'beautytips', 'naturkosmetik', 'routine', 'makeuplook'],
    captions: [
      '{n} Produkte. Nur zwei davon braucht ihr wirklich. {emoji}',
      '{topic} - und nein, das ist kein Werbepost.',
      'Links: 4 Euro. Rechts: 68 Euro. Ergebnis: entscheidet selbst.',
      'Haut ist kein Projekt. Trotzdem hier meine Routine. {emoji}',
      'Nach {n} Wochen sieht man endlich einen Unterschied.',
      'Ungeschminkt, ungefiltert, unspektakulaer. Und das ist okay.',
    ],
    comments: [
      'Welches Produkt ist das genau?',
      'Danke, dass du ehrlich bist ❤️',
      'Deine Haut ist ein Traum',
      'Ich probiere das sofort',
      'Endlich jemand ohne Filter',
      'Mehr solche Vergleiche bitte!',
    ],
    bios: [
      'Skincare ohne Marketing-Bullshit 💄',
      'Make-up Artist | Buchungen offen',
      'Drogerie-Finds & ehrliche Tests',
      'Naturkosmetik | Inhaltsstoffe erklaert',
    ],
    styles: ['pastel', 'studio', 'vivid'],
  },
  lifestyle: {
    id: 'lifestyle',
    label: 'Lifestyle',
    emoji: '🌿',
    palette: ['#d4fc79', '#96e6a1', '#2d3a2e', '#fbfff5'],
    motif: 'abstract',
    reach: 0.84,
    competition: 0.82,
    topics: [
      { id: 'morgen', label: 'Morgenroutine', broad: 0.84, core: 0.86 },
      { id: 'wohnung', label: 'Wohnungs-Tour', broad: 0.86, core: 0.84 },
      { id: 'produktiv', label: 'Produktivitaets-System', broad: 0.8, core: 0.88 },
      { id: 'minimal', label: 'Ausmisten', broad: 0.82, core: 0.86 },
      { id: 'mentalhealth', label: 'Ehrlich ueber schlechte Tage', broad: 0.9, core: 0.84 },
      { id: 'geld', label: 'Wie ich spare', broad: 0.88, core: 0.8 },
      { id: 'sonntag', label: 'Slow Sunday', broad: 0.64, core: 0.72 },
      { id: 'buch', label: 'Buch des Monats', broad: 0.58, core: 0.74 },
    ],
    hashtags: ['lifestyle', 'morgenroutine', 'minimalismus', 'selfcare', 'produktivitaet', 'wohnen', 'interior', 'slowliving', 'achtsamkeit', 'mentalhealth', 'alltag', 'balance', 'journaling', 'routine'],
    captions: [
      '5:30 Uhr. Kein Handy bis 7. Das hat alles veraendert. {emoji}',
      '{topic}. Klingt banal, hat bei mir aber {n} Monate gedauert.',
      'Ich habe {n} Dinge weggegeben und vermisse genau null davon.',
      'Nicht jeder Tag ist aesthetisch. Heute war er es zufaellig. {emoji}',
      'Ehrlich: letzte Woche ging gar nichts. Diese Woche wieder.',
      'Kleine Systeme schlagen grosse Vorsaetze.',
    ],
    comments: [
      'So wahr, danke dafuer 🙏',
      'Woher ist die Lampe?',
      'Deine Ehrlichkeit tut gut',
      'Ich starte morgen damit',
      'Wie haeltst du das durch?',
      'Speicher ich mir fuer Januar 😄',
    ],
    bios: [
      'Langsam leben in einer schnellen Stadt 🌿',
      'Routinen, Ordnung, Ruhe',
      'Minimalismus fuer Menschen mit Kram',
      'Ehrlich ueber Alltag & Kopf',
    ],
    styles: ['pastel', 'film', 'golden'],
  },
  cars: {
    id: 'cars',
    label: 'Autos',
    emoji: '🚗',
    palette: ['#141e30', '#243b55', '#ff6a00', '#eef2f7'],
    motif: 'skyline',
    reach: 0.76,
    competition: 0.58,
    topics: [
      { id: 'build', label: 'Umbau-Fortschritt', broad: 0.74, core: 0.9 },
      { id: 'youngtimer', label: 'Youngtimer-Fund', broad: 0.8, core: 0.86 },
      { id: 'detail', label: 'Detail-Aufnahme', broad: 0.6, core: 0.72 },
      { id: 'roadtrip', label: 'Passstrasse gefahren', broad: 0.82, core: 0.8 },
      { id: 'werkstatt', label: 'Werkstatt-Realitaet', broad: 0.76, core: 0.84 },
      { id: 'ev', label: 'Elektro vs. Verbrenner', broad: 0.88, core: 0.7 },
      { id: 'kosten', label: 'Was es wirklich kostet', broad: 0.86, core: 0.82 },
      { id: 'treffen', label: 'Car-Meet', broad: 0.7, core: 0.78 },
    ],
    hashtags: ['auto', 'cars', 'youngtimer', 'carsofinstagram', 'tuning', 'werkstatt', 'roadtrip', 'oldtimer', 'motorsport', 'schrauber', 'carspotting', 'elektroauto', 'carmeet', 'petrolhead'],
    captions: [
      '{n} Stunden Arbeit, ein Teil fehlt noch. Klassiker. {emoji}',
      '{topic}. Zahlen und Teile in den Kommentaren.',
      'Gekauft fuer {n}00 Euro, gerettet aus einer Scheune.',
      'Kein Sound der Welt ersetzt das hier. {emoji}',
      'Schoen ist relativ. Selbst gemacht ist absolut.',
      'Realitaetscheck: die Rechnung war hoeher als der Wagen wert ist.',
    ],
    comments: [
      'Was fuer ein Brett 🔥',
      'Welche Felgen sind das?',
      'Respekt fuer die Arbeit',
      'Sound-Video bitte!',
      'Mein Traumauto seit ich Kind bin',
      'Original erhalten ist immer richtig',
    ],
    bios: [
      'Schraube mehr als ich fahre 🔧',
      'Youngtimer & schlechte Entscheidungen',
      'Alles ueber E30 | Umbau-Doku',
      'Passstrassen & Kaffeepausen ☕',
    ],
    styles: ['moody', 'vivid', 'mono'],
  },
  nature: {
    id: 'nature',
    label: 'Natur',
    emoji: '🌲',
    palette: ['#134e5e', '#71b280', '#0d2118', '#f2fff7'],
    motif: 'mountain',
    reach: 0.83,
    competition: 0.52,
    topics: [
      { id: 'wandern', label: 'Wanderung', broad: 0.78, core: 0.88 },
      { id: 'tiere', label: 'Wildtier-Beobachtung', broad: 0.88, core: 0.86 },
      { id: 'jahreszeit', label: 'Jahreszeiten-Wechsel', broad: 0.74, core: 0.8 },
      { id: 'camping', label: 'Camping im Nirgendwo', broad: 0.82, core: 0.84 },
      { id: 'umwelt', label: 'Umweltschutz-Thema', broad: 0.76, core: 0.82 },
      { id: 'pflanzen', label: 'Pflanzen bestimmen', broad: 0.6, core: 0.84 },
      { id: 'nebel', label: 'Nebelmorgen', broad: 0.72, core: 0.74 },
      { id: 'route', label: 'Tourenbeschreibung', broad: 0.64, core: 0.88 },
    ],
    hashtags: ['natur', 'wandern', 'outdoor', 'berge', 'wald', 'camping', 'naturfotografie', 'nachhaltigkeit', 'hiking', 'wildlife', 'sonnenaufgang', 'see', 'umweltschutz', 'draussen'],
    captions: [
      '{n} Kilometer, 900 Hoehenmeter, ein Bild. Hat sich gelohnt. {emoji}',
      '{topic}. Route findet ihr in den Kommentaren.',
      'Handy aus, Kopf leer, Beine schwer. Perfekt.',
      'Der Nebel hing genau {n} Minuten so. Danach war alles grau. {emoji}',
      'Nehmt euren Muell wieder mit. Danke.',
      'Draussen ist kein Hobby, sondern ein Grundbeduerfnis.',
    ],
    comments: [
      'Wo ist das? Sieht magisch aus',
      'Genau deshalb liebe ich Herbst 🍂',
      'Beste Route, bin ich letztes Jahr gegangen',
      'Danke fuer die Erinnerung, rauszugehen',
      'Diese Stille sieht man dem Bild an',
      'Welche Ausruestung nimmst du mit?',
    ],
    bios: [
      'Draussen statt drinnen 🌲',
      'Wandern, Zelten, Kaffee kochen',
      'Naturfotografie aus dem Schwarzwald',
      'Nachhaltig unterwegs | Leave no trace',
    ],
    styles: ['moody', 'film', 'golden'],
  },
  comedy: {
    id: 'comedy',
    label: 'Comedy',
    emoji: '😂',
    palette: ['#f7971e', '#ffd200', '#2a1a00', '#fffdf2'],
    motif: 'abstract',
    reach: 0.98,
    competition: 0.86,
    topics: [
      { id: 'alltag', label: 'Alltagsbeobachtung', broad: 0.94, core: 0.88 },
      { id: 'sketch', label: 'Kurzer Sketch', broad: 0.92, core: 0.9 },
      { id: 'meme', label: 'Meme zum Zeitgeschehen', broad: 0.96, core: 0.82 },
      { id: 'eltern', label: 'Eltern vs. Kinder', broad: 0.9, core: 0.84 },
      { id: 'buero', label: 'Buero-Wahnsinn', broad: 0.88, core: 0.86 },
      { id: 'dialekt', label: 'Dialekt-Comedy', broad: 0.8, core: 0.88 },
      { id: 'selbstironie', label: 'Selbstironie', broad: 0.86, core: 0.8 },
      { id: 'reaction', label: 'Reaction auf Kommentare', broad: 0.84, core: 0.78 },
    ],
    hashtags: ['comedy', 'lustig', 'humor', 'meme', 'sketch', 'lachen', 'alltag', 'satire', 'witzig', 'funny', 'buerohumor', 'eltern', 'dialekt', 'memesdeutsch'],
    captions: [
      'Wer kennt es? Bitte sagt mir, dass ich nicht allein bin. {emoji}',
      '{topic}. Zu real? Tut mir leid.',
      'Meine Mutter hat das gesehen und nur genickt.',
      'Teil {n} von einer Serie, die niemand wollte. {emoji}',
      'Ich lache, damit ich nicht weine. Kommentare sind offen.',
      'Markiere die Person, die genau so ist.',
    ],
    comments: [
      'Ich bin tot 😂😂',
      'Das bin zu 100% ich',
      'Markiere jemanden... ich markiere mich selbst',
      'Warum ist das so genau richtig',
      'Serie bitte weiterfuehren!',
      'Teil 2 wann?',
    ],
    bios: [
      'Mache Witze ueber mein eigenes Leben 😂',
      'Alltagscomedy | jeden Dienstag neu',
      'Nicht witzig, nur ehrlich',
      'Sketche aus dem Grossraumbuero',
    ],
    styles: ['vivid', 'neon', 'pastel'],
  },
  dance: {
    id: 'dance',
    label: 'Tanz',
    emoji: '💃',
    palette: ['#ee0979', '#ff6a00', '#1a0014', '#fff2f7'],
    motif: 'stage',
    reach: 0.9,
    competition: 0.84,
    topics: [
      { id: 'choreo', label: 'Neue Choreografie', broad: 0.86, core: 0.9 },
      { id: 'tutorial', label: 'Schritt fuer Schritt', broad: 0.84, core: 0.9 },
      { id: 'freestyle', label: 'Freestyle', broad: 0.8, core: 0.84 },
      { id: 'battle', label: 'Battle-Ausschnitt', broad: 0.88, core: 0.86 },
      { id: 'probe', label: 'Probenalltag', broad: 0.62, core: 0.78 },
      { id: 'duo', label: 'Duo mit Freund/in', broad: 0.9, core: 0.82 },
      { id: 'ballett', label: 'Klassisches Training', broad: 0.7, core: 0.8 },
      { id: 'fail', label: 'Outtakes', broad: 0.84, core: 0.72 },
    ],
    hashtags: ['tanzen', 'dance', 'choreografie', 'hiphopdance', 'ballett', 'dancer', 'freestyle', 'dancebattle', 'tanzstudio', 'moves', 'tanzvideo', 'urbandance', 'training', 'performance'],
    captions: [
      '{n} Durchlaeufe fuer 15 Sekunden. Es hat sich gelohnt. {emoji}',
      '{topic}. Tutorial kommt, wenn dieser Post 500 Likes bekommt.',
      'Erster Take vs. letzter Take. Unterschied wie Tag und Nacht.',
      'Meine Beine sagen nein, mein Kopf sagt nochmal. {emoji}',
      'Tanzen ist die einzige Sprache, in der ich fliessend bin.',
      'Outtakes am Ende. Ja, ich bin hingefallen.',
    ],
    comments: [
      'Deine Isolationen sind unfassbar',
      'Tutorial bitte!! 🙏',
      'Wie lange tanzt du schon?',
      'Der Beat und du seid eins',
      'Ich uebe das seit Wochen und schaffe es nicht',
      'Outtakes sind mein Lieblingsteil 😂',
    ],
    bios: [
      'Hip-Hop & Contemporary | Studio Koeln',
      'Tanze, seit ich laufen kann 💃',
      'Choreografin | Workshops buchbar',
      'Battle-Dancer | Freestyle ueber alles',
    ],
    styles: ['neon', 'vivid', 'moody'],
  },
};

export const NICHE_IDS = Object.keys(NICHES) as NicheId[];

/** Allgemeine Kommentare, die zu jedem Post passen. */
export const GENERIC_COMMENTS = [
  'Stark! 🔥',
  'Mega ❤️',
  'Wow 😍',
  'Das ist richtig gut geworden',
  'Folge dir seit heute',
  'Deine Feed-Aesthetik ist konsistent, Respekt',
  'Mehr davon bitte',
  'Wie machst du das nur',
  'Das erste Mal, dass mir der Algorithmus was Gutes zeigt',
  'Kommt in meine Sammlung',
  '👏👏👏',
  'Qualitaet wie immer',
];

/** Kommentare von Hatern - tauchen ab einer gewissen Reichweite auf. */
export const HATER_COMMENTS = [
  'Geklaut von einem groesseren Account',
  'Wieder nur Werbung, langweilig',
  'Frueher warst du besser',
  'Gekaufte Follower sieht man sofort',
  'Warum pusht der Algorithmus so einen Muell',
  'Reichweite ist nicht gleich Talent',
];

/** Kommentare von Fans der eigenen Community. */
export const FAN_COMMENTS = [
  'Bin seit {n} Followern dabei, schoen dich wachsen zu sehen ❤️',
  'Du verdienst so viel mehr Reichweite',
  'Erster! Wie immer 😄',
  'Habe auf diesen Post gewartet',
  'Deine Posts machen meinen Tag besser',
  'Ich empfehle dich staendig weiter',
];

export const STYLE_LABELS: Record<string, { label: string; hint: string }> = {
  vivid: { label: 'Vivid', hint: 'Knallige Farben, hoher Kontrast' },
  film: { label: 'Film', hint: 'Analoge Koernung, warme Toene' },
  mono: { label: 'Mono', hint: 'Schwarzweiss, grafisch' },
  golden: { label: 'Golden Hour', hint: 'Warmes Abendlicht' },
  studio: { label: 'Studio', hint: 'Sauber, hell, professionell' },
  neon: { label: 'Neon', hint: 'Nacht, Farben, Energie' },
  pastel: { label: 'Pastell', hint: 'Weich, hell, ruhig' },
  moody: { label: 'Moody', hint: 'Dunkel, dramatisch, tief' },
};

/** Findet ein Thema anhand seiner Id - faellt auf das erste Thema zurueck. */
export function getTopic(niche: NicheId, topicId: string): Topic {
  const list = NICHES[niche].topics;
  return list.find((t) => t.id === topicId) ?? list[0];
}

/** Wie gut ein Bildstil zu einer Nische passt (0..1). */
export function styleFit(niche: NicheId, style: string): number {
  const preferred = NICHES[niche].styles;
  const idx = preferred.indexOf(style);
  if (idx === 0) return 1;
  if (idx === 1) return 0.88;
  if (idx > 1) return 0.78;
  return 0.5;
}
